// Generated by LiveScript 1.6.0
(function(){
  module.exports = function(){
    var width, ref$, height, ref1$;
    width = Math.max((typeof document != 'undefined' && document !== null ? (ref$ = document.documentElement) != null ? ref$.clientWidth : void 8 : void 8) || 0, (typeof window != 'undefined' && window !== null ? window.innerWidth : void 8) || 0);
    height = Math.max((typeof document != 'undefined' && document !== null ? (ref1$ = document.documentElement) != null ? ref1$.clientHeight : void 8 : void 8) || 0, (typeof window != 'undefined' && window !== null ? window.innerHeight : void 8) || 0);
    return {
      width: width,
      height: height
    };
  };
}).call(this);
