// Generated by LiveScript 1.6.0
(function(){
  module.exports = function(){
    var m, ref$, r;
    m = Math.max(typeof document != 'undefined' && document !== null ? (ref$ = document.documentElement) != null ? ref$.clientWidth : void 8 : void 8, (typeof window != 'undefined' && window !== null ? window.innerWidth : void 8) || 0);
    return r = (function(){
      switch (false) {
      case !(m > 800):
        return 'desktop';
      default:
        return 'mobile';
      }
    }());
  };
}).call(this);
