// Generated by LiveScript 1.6.0
(function(){
  var eth, insight, bitcore, blockstream, insight_segwit, erc20, vlxerc20, omni, velas2;
  eth = require('../web3t/providers/eth.js');
  insight = require('../web3t/providers/insight.js');
  bitcore = require('../web3t/providers/bitcore.js');
  blockstream = require('../web3t/providers/blockstream.js');
  insight_segwit = require('../web3t/providers/insight_segwit.js');
  erc20 = require('../web3t/providers/erc20.js');
  vlxerc20 = require('../web3t/providers/vlxerc20.js');
  omni = require('../web3t/providers/omni.js');
  velas2 = require('../web3t/providers/velas2.js');
  module.exports = {
    eth: eth,
    insight: insight,
    bitcore: bitcore,
    blockstream: blockstream,
    insight_segwit: insight_segwit,
    erc20: erc20,
    omni: omni,
    velas2: velas2,
    vlxerc20: vlxerc20
  };
}).call(this);
