// Generated by LiveScript 1.6.0
(function(){
  var ethnamed, getRecord;
  ethnamed = require('../api/ethnamed.js');
  getRecord = require('./get-record.js');
  module.exports = function(web3, store, cb){
    var whois, record;
    whois = ethnamed(web3).whois;
    record = getRecord(store);
    return whois(record, function(err, data){
      if (err != null) {
        return cb(err);
      }
      return cb(null, data);
    });
  };
}).call(this);
