// Generated by LiveScript 1.6.0
(function(){
  var velasWeb3, addresses, abis;
  velasWeb3 = require('./velas-web3.js');
  addresses = require('./addresses.js');
  abis = {
    Staking: require("./contracts/StakingAuRa.json").abi,
    ValidatorSet: require("./contracts/ValidatorSetAuRa.json").abi,
    BlockReward: require("./contracts/BlockRewardAuRa.json").abi,
    Development: require("./contracts/VelasDevelopment.json").abi
  };
  module.exports = function(store){
    var web3, api, ref$, ref1$, ref2$, ref3$, ref4$;
    web3 = velasWeb3(store);
    api = {
      Staking: typeof (ref$ = web3.eth).contract == 'function' ? (ref1$ = ref$.contract(abis.Staking)) != null ? ref1$.at(addresses.Staking) : void 8 : void 8,
      ValidatorSet: typeof (ref$ = web3.eth).contract == 'function' ? (ref2$ = ref$.contract(abis.ValidatorSet)) != null ? ref2$.at(addresses.ValidatorSet) : void 8 : void 8,
      BlockReward: typeof (ref$ = web3.eth).contract == 'function' ? (ref3$ = ref$.contract(abis.BlockReward)) != null ? ref3$.at(addresses.BlockReward) : void 8 : void 8,
      Development: typeof (ref$ = web3.eth).contract == 'function' ? (ref4$ = ref$.contract(abis.Development)) != null ? ref4$.at(addresses.Development) : void 8 : void 8,
      web3: web3.eth
    };
    return api;
  };
}).call(this);
