// Generated by LiveScript 1.6.0
(function(){
  var global, react, observable, observer, Store, pages, StartPage, web3t, Main, buildWalletInfo, store, App;
  global = require('./global.js');
  react = require('react');
  observable = require('mobx').observable;
  observer = require('mobx-react').observer;
  Store = require('./Store.js');
  pages = require('./Pages.js');
  StartPage = require('./pages/StartPage.js');
  web3t = require('./web3t.js');
  Main = observer(function(arg$){
    var store;
    store = arg$.store;
    return pages['default'][store.tab]({
      store: store,
      web3t: web3t
    });
  });
  buildWalletInfo = function(token){
    return {
      token: token,
      logo: web3t[token].getConfig().image,
      balance: "0"
    };
  };
  store = observable(Store['default']);
  module.exports = App = (function(superclass){
    var prototype = extend$((import$(App, superclass).displayName = 'App', App), superclass).prototype, constructor = App;
    App.prototype.render = function(){
      var store;
      return Main.pug(store = store);
    };
    function App(){
      App.superclass.apply(this, arguments);
    }
    return App;
  }(react.Component));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
